services:
  electric-sync-service:
    container_name: electric-sync-service
    image: electricsql/electric:latest
    environment:
      DATABASE_URL: ${SUPABASE_DATABASE_URL}
      DATABASE_REQUIRE_SSL: false
      ELECTRIC_WRITE_TO_PG_MODE: direct_writes
      LOGICAL_PUBLISHER_HOST: electric-sync-service
      PG_PROXY_PASSWORD: proxy_password
      AUTH_MODE: secure
      AUTH_JWT_ALG: ES256
      AUTH_JWT_KEY: ${ELECTRIC_PRIVATE_KEY_ES256}
      AUTH_JWT_ISS: cella_backend
      AUTH_JWT_AUD: cella_client
      LOG_LEVEL: debug
    ports:
      - 5133:5133
      - 65432:65432
    restart: always