version: "3.1"

volumes:
  pg_data:

services:
  pg:
    image: postgres:14-alpine
    container_name: electric_db
    environment:
      POSTGRES_PASSWORD: pg_password
    command:
      - -c
      - wal_level=logical
    ports:
      - 5431:5431
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  electric:
    image: electricsql/electric
    container_name: electric-sync-service
    depends_on:
      - pg
    environment:
      DATABASE_URL: postgresql://postgres:pg_password@pg/postgres
      DATABASE_REQUIRE_SSL: false
      LOGICAL_PUBLISHER_HOST: electric
      PG_PROXY_PASSWORD: proxy_password
      AUTH_MODE: insecure
    ports:
      - 5133:5133
      - 65432:65432
    restart: always